version: "3"
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "5000:5000"
    container_name: mulheres-palestrantes-frontend
    env_file: .env
